### ISSUE TITLE
Web上使用文字显示不出来

### ISSUE THREAD

**Issue by limhGeek** [Fliggy-Mobile/fbutton#1]
Fbutton 在web上使用，限制高度为40后，文字显示不全

**Comment by chenBingX** [comment]
你好，方便提供一下有问题的这段代码吗？😃

**Comment by limhGeek** [comment]
只要给FButton设置高度，里面内容就显示不出来了，你们试试



---原始邮件---
发件人: "CoorChice"<notifications@github.com&gt;
发送时间: 2020年5月14日(周四) 下午3:30
收件人: "Fliggy-Mobile/fbutton"<fbutton@noreply.github.com&gt;;
抄送: "limh"<1591054297@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Fliggy-Mobile/fbutton] Web上使用文字显示不出来 (#1)




 
你好，方便提供一下有问题的这段代码吗？😃

**Comment by chenBingX** [comment]
你好开发者，在 **FButton** 中，由于考虑到只设置文字，而没设置尺寸的场景下的展示问题，会默认有一个内间距 Padding。它的大小是：`EdgeInsets.symmetric(horizontal: 16.0, vertical: 16)`。目前，你可以通过为 **FButton** 配置 `padding` 属性覆盖该默认配置。

```dart
FButton(
  padding: EdgeInsets.zero,
)
```

在后续的版本中，我们会仔细评估在配置了尺寸信息后，是否应该自动去掉默认内间距。欢迎保持对 **FWidget** 的关注哦！😄

**Comment by chenBingX** [comment]
Hi,
 在最新的 **1.1.0** 版本中， **FButton** 的默认内间距遭到了移除。  

新版依赖方式：
```
fbutton: ^1.1.0
```
