### ISSUE TITLE
loading里面的图标我能换成自己gif嘛

### ISSUE THREAD

**Issue by co3318co** [Fliggy-Mobile/fbutton#3]

**Comment by co3318co** [comment]
还有button里面text跟image布局想调整里面的位置嘛  希望越来越强大 我们这些开发者也可以越来越爽.阿里威武

**Comment by co3318co** [comment]
点击了loading之后 button颜色会变 而且button 宽度高度不会变化 代码也是按照你给的demo写的 你点击之后 button会改变宽度高度 是哪个方法呢 我想实现点击button之后 button的尺寸只有loading的大小

**Comment by co3318co** [comment]
只要设置了disabledColor颜色 点击loading图片会变为disa的颜色 麻烦大神看一下  阿里 永远滴神

**Comment by chenBingX** [comment]
1. 只需要在点击 **loading** 的时候，将 `width` 和 `height` 取消即可
2. **loading** 状态下，FButton 是处于不可用状态的，所以会使用不可用状态的颜色状态

**Comment by co3318co** [comment]
阿里 永远滴神 谢谢

**Comment by chenBingX** [comment]
你好，在最新的 2.0.0 版本中，已经添加了你提议的自定义 loading 样式支持。
欢迎继续保持对 FWidget 的关注哦😄
