### ISSUE TITLE
strokeWidth和strokeColor设置无效

### ISSUE THREAD

**Issue by Smiacter** [Fliggy-Mobile/fbutton#4]
1.1.0中，strokeWidth和strokeColor设置无效，copy你的代码直接使用也是，在loading状态下有效果！

**Comment by JasonHezz** [comment]
https://github.com/Fliggy-Mobile/fbutton/blob/2fbe2b8b37afbd01af94f4bcd86117ee14566024/lib/fbutton.dart#L426-L430

```
enabled 
         ? strokeColor ?? Colors.transparent 
```
查看了下应该是更新1.1.0 的时候 修改错误导致的 稍后提交PR

**Comment by Smiacter** [comment]
> https://github.com/Fliggy-Mobile/fbutton/blob/2fbe2b8b37afbd01af94f4bcd86117ee14566024/lib/fbutton.dart#L426-L430
> 
> ```
> enabled 
>          ? strokeColor ?? Colors.transparent 
> ```
> 
> 查看了下应该是更新1.1.0 的时候 修改错误导致的 稍后提交PR

👍，我没有去看他的源码

**Comment by chenBingX** [comment]
你好，在最新的 2.0.0 版本中，这个问题已经得到修复。
欢迎继续保持对 FWidget 的关注哦😄
